import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": " الملاحظات",
          "2": "العربية",
          "3": "الانجليزية",
          "4": "الملف الشخصي",
          "5": "الاعدادات",
          "6": "تسجيل الخروج",
          "7": "اللغة",
          "8": " الثيمات",
          "9": " الاشعارات",
          "10": " اضافة ملاحظة",
          "11": " الملاحظة",
          "12": " عنوانها",
          "13": " اللون",
          "14": " تعديل الملاحظة",
          "15": "البريد الالكتروني",
          "16": "كلمة السر",
          "17": " ليس لديك حساب؟",
          "18": "انشاء حساب",
          "19": "تسجيل الدخول",
          "20": "رقم الجوال",
          "21": "لديك حساب بالفعل؟",
          "22": "هنالك خطأ في البريد الالكتروني أو كلمة السر",
          "23": " البيانات غير صحيحة",
          "24": "تحذير",
          "25": "هل أنت متأكد من الحذف؟",
          "26": "نعم",
          "27": "لا",
          "28": "الوضع الليلي",
          "29": "وضع النهار"
        },
        "en": {
          "1": "Notes",
          "2": "Arabic",
          "3": " English",
          "4": "Profile",
          "5": "Settings",
          "6": "LogOut",
          "7": "Languge",
          "8": "Themes",
          "9": " Notification",
          "10": "Add Notes",
          "11": "Note",
          "12": "Title",
          "13": "Color",
          "14": "Edit Notes",
          "15": "Email Address",
          "16": "Password",
          "17": "Don\'t have accaont?",
          "18": "SingUp",
          "19": "Login",
          "20": "Phone Number",
          "21": "Have accaont?",
          "22": "There is an error in the email or password",
          "23": "The data is incorrect",
          "24": "Warning",
          "25": "Are you sure you want to delete?",
          "26": "Yes",
          "27": "No",
          "28": "Dark mode",
          "29": "light mode"
        }
      };
}
//